// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nt.proxy;

import com.sun.xml.rpc.encoding.*;
import com.sun.xml.rpc.client.ServiceExceptionImpl;
import com.sun.xml.rpc.util.exception.*;
import com.sun.xml.rpc.soap.SOAPVersion;
import com.sun.xml.rpc.client.HandlerChainImpl;
import javax.xml.rpc.*;
import javax.xml.rpc.encoding.*;
import javax.xml.rpc.handler.HandlerChain;
import javax.xml.rpc.handler.HandlerInfo;
import javax.xml.namespace.QName;

public class Hello_Impl extends com.sun.xml.rpc.client.BasicService implements Hello {
    private static final QName serviceName = new QName("http://service.hello.com/wsdl", "Hello");
    private static final QName ns1_IHelloServicePort_QNAME = new QName("http://service.hello.com/wsdl", "IHelloServicePort");
    private static final Class IHelloService_PortClass = com.nt.proxy.IHelloService.class;
    
    public Hello_Impl() {
        super(serviceName, new QName[] {
                        ns1_IHelloServicePort_QNAME
                    },
            new com.nt.proxy.Hello_SerializerRegistry().getRegistry());
        
    }
    
    public java.rmi.Remote getPort(javax.xml.namespace.QName portName, java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (portName.equals(ns1_IHelloServicePort_QNAME) &&
                serviceDefInterface.equals(IHelloService_PortClass)) {
                return getIHelloServicePort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(portName, serviceDefInterface);
    }
    
    public java.rmi.Remote getPort(java.lang.Class serviceDefInterface) throws javax.xml.rpc.ServiceException {
        try {
            if (serviceDefInterface.equals(IHelloService_PortClass)) {
                return getIHelloServicePort();
            }
        } catch (Exception e) {
            throw new ServiceExceptionImpl(new LocalizableExceptionAdapter(e));
        }
        return super.getPort(serviceDefInterface);
    }
    
    public com.nt.proxy.IHelloService getIHelloServicePort() {
        java.lang.String[] roles = new java.lang.String[] {};
        HandlerChainImpl handlerChain = new HandlerChainImpl(getHandlerRegistry().getHandlerChain(ns1_IHelloServicePort_QNAME));
        handlerChain.setRoles(roles);
        com.nt.proxy.IHelloService_Stub stub = new com.nt.proxy.IHelloService_Stub(handlerChain);
        try {
            stub._initialize(super.internalTypeRegistry);
        } catch (JAXRPCException e) {
            throw e;
        } catch (Exception e) {
            throw new JAXRPCException(e.getMessage(), e);
        }
        return stub;
    }
}
