// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nt.proxy;

public interface IHelloService extends java.rmi.Remote {
    public java.lang.String wish(java.lang.String string_1) throws 
         java.rmi.RemoteException;
}
