// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nt.proxy;


public class GetCitiesByCountryResponse {
    protected java.lang.String getCitiesByCountryResult;
    
    public GetCitiesByCountryResponse() {
    }
    
    public GetCitiesByCountryResponse(java.lang.String getCitiesByCountryResult) {
        this.getCitiesByCountryResult = getCitiesByCountryResult;
    }
    
    public java.lang.String getGetCitiesByCountryResult() {
        return getCitiesByCountryResult;
    }
    
    public void setGetCitiesByCountryResult(java.lang.String getCitiesByCountryResult) {
        this.getCitiesByCountryResult = getCitiesByCountryResult;
    }
}
