// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nt.proxy;


public class GetCitiesByCountry {
    protected java.lang.String countryName;
    
    public GetCitiesByCountry() {
    }
    
    public GetCitiesByCountry(java.lang.String countryName) {
        this.countryName = countryName;
    }
    
    public java.lang.String getCountryName() {
        return countryName;
    }
    
    public void setCountryName(java.lang.String countryName) {
        this.countryName = countryName;
    }
}
