// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nt.proxy;


public class GetWeatherResponse {
    protected java.lang.String getWeatherResult;
    
    public GetWeatherResponse() {
    }
    
    public GetWeatherResponse(java.lang.String getWeatherResult) {
        this.getWeatherResult = getWeatherResult;
    }
    
    public java.lang.String getGetWeatherResult() {
        return getWeatherResult;
    }
    
    public void setGetWeatherResult(java.lang.String getWeatherResult) {
        this.getWeatherResult = getWeatherResult;
    }
}
