// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nt.proxy;


public class GetWeather {
    protected java.lang.String cityName;
    protected java.lang.String countryName;
    
    public GetWeather() {
    }
    
    public GetWeather(java.lang.String cityName, java.lang.String countryName) {
        this.cityName = cityName;
        this.countryName = countryName;
    }
    
    public java.lang.String getCityName() {
        return cityName;
    }
    
    public void setCityName(java.lang.String cityName) {
        this.cityName = cityName;
    }
    
    public java.lang.String getCountryName() {
        return countryName;
    }
    
    public void setCountryName(java.lang.String countryName) {
        this.countryName = countryName;
    }
}
