// This class was generated by the JAXRPC SI, do not edit.
// Contents subject to change without notice.
// JAX-RPC Standard Implementation (1.1.3, build R1)
// Generated source version: 1.1.3

package com.nt.proxy;

public interface GlobalWeatherSoap extends java.rmi.Remote {
    public java.lang.String getWeather(java.lang.String cityName, java.lang.String countryName) throws 
         java.rmi.RemoteException;
    public java.lang.String getCitiesByCountry(java.lang.String countryName) throws 
         java.rmi.RemoteException;
}
